// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDXFwSmN1D4jnwJiPwVH1MfYjaHzPaszZI',
    appId: '1:1020024730402:web:957c33d8befb83daedeb7b',
    messagingSenderId: '1020024730402',
    projectId: 'readify-aiml',
    authDomain: 'readify-aiml.firebaseapp.com',
    storageBucket: 'readify-aiml.appspot.com',
    measurementId: 'G-1L6K6KKZ19',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCQISIxHyrYWo9dGiDmGbgRbK1J1Cm7444',
    appId: '1:1020024730402:android:98687f20720dbacaedeb7b',
    messagingSenderId: '1020024730402',
    projectId: 'readify-aiml',
    storageBucket: 'readify-aiml.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCVZl4PLuiWIOWnwxutA7IX8_SgnbL6bPI',
    appId: '1:1020024730402:ios:76283dec5cf3bad6edeb7b',
    messagingSenderId: '1020024730402',
    projectId: 'readify-aiml',
    storageBucket: 'readify-aiml.appspot.com',
    iosBundleId: 'com.example.readify',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCVZl4PLuiWIOWnwxutA7IX8_SgnbL6bPI',
    appId: '1:1020024730402:ios:76283dec5cf3bad6edeb7b',
    messagingSenderId: '1020024730402',
    projectId: 'readify-aiml',
    storageBucket: 'readify-aiml.appspot.com',
    iosBundleId: 'com.example.readify',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDXFwSmN1D4jnwJiPwVH1MfYjaHzPaszZI',
    appId: '1:1020024730402:web:f2cf92df957389daedeb7b',
    messagingSenderId: '1020024730402',
    projectId: 'readify-aiml',
    authDomain: 'readify-aiml.firebaseapp.com',
    storageBucket: 'readify-aiml.appspot.com',
    measurementId: 'G-Z1R49973SP',
  );

}