name: readify
description: "A new Flutter project."
publish_to: "none" # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ">=3.4.1 <4.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.6
  firebase_core: ^3.4.0
  firebase_auth: ^5.2.0
  flutter_html: ^3.0.0-beta.2
  cloud_firestore: ^5.4.0
  flutter_pdfview: ^1.3.2
  epubx: ^4.0.0
  google_fonts: ^6.2.1
  webview_flutter: ^4.10.0
  scrollable_positioned_list: ^0.3.5
  shared_preferences: ^2.3.2
  path_provider_android: ^2.0.14
  flutter_tts: ^4.2.0
  smooth_page_indicator: ^1.1.0
  flutter_animate: ^4.1.1+1

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/book_cover_1.jpeg
    - assets/book_cover_2.jpeg
    - assets/book_cover_3.jpeg
    - assets/book_cover_4.jpeg
    - assets/main_bg.jpeg
    - assets/secong_bg.jpeg
    - assets/immortals_of_meluha.epub
    - assets/secret_of_the_nagas.epub
    - assets/book_3.epub
    - assets/oath_of_the_vayuputras.epub
